"""Extract the glyph outlines the glyph skin needs into a plain data module.

Run once, by hand, when the set of characters changes:

    python scripts/build_glyph_outlines.py > src/vimol/glyph_outlines.py

The point of baking them is that vimol then carries no font machinery at all --
no fontTools, no freetype, no Pillow (see the README) -- and renders the same
letterforms on every machine, rather than whatever the host happens to have
installed. Only this script needs fontTools, and only when the data is rebuilt.

The face is DejaVu Sans Bold, which ships with matplotlib under the Bitstream
Vera license: permissive, and compatible with vimol's MIT. Bold because these
letters are printed onto shaded, curved solids at a couple of dozen pixels --
regular weight stems come out pale and broken there. Helvetica is deliberately
not used -- it is proprietary, and its outlines are not ours to redistribute.
"""
import os

import matplotlib
from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

CHARS = "ABCDEFGHIKLMNOPQRSTUVWXY" + "0123456789"
CURVE_STEPS = 8          # segments per curve; a cap-height glyph needs no more


class Flatten(BasePen):
    """Collects closed contours as flat point lists."""

    def __init__(self, glyphset):
        super().__init__(glyphset)
        self.contours, self._current = [], []

    def _moveTo(self, pt):
        self._closePath()
        self._current = [pt]

    def _lineTo(self, pt):
        self._current.append(pt)

    def _curveToOne(self, p1, p2, p3):
        p0 = self._current[-1]
        for i in range(1, CURVE_STEPS + 1):
            t = i / CURVE_STEPS
            u = 1.0 - t
            self._current.append((
                u**3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0],
                u**3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1]))

    def _qCurveToOne(self, p1, p2):
        p0 = self._current[-1]
        for i in range(1, CURVE_STEPS + 1):
            t = i / CURVE_STEPS
            u = 1.0 - t
            self._current.append((u * u * p0[0] + 2 * u * t * p1[0] + t * t * p2[0],
                                  u * u * p0[1] + 2 * u * t * p1[1] + t * t * p2[1]))

    def _closePath(self):
        if len(self._current) > 2:
            self.contours.append(self._current)
        self._current = []

    _endPath = _closePath


def main() -> None:
    path = os.path.join(os.path.dirname(matplotlib.__file__),
                        "mpl-data", "fonts", "ttf", "DejaVuSans-Bold.ttf")
    font = TTFont(path)
    glyphset = font.getGlyphSet()
    cmap = font.getBestCmap()
    upem = font["head"].unitsPerEm
    # Older OS/2 tables carry no sCapHeight; measuring the H is what the value
    # would have recorded anyway, and it needs no version check.
    cap = getattr(font["OS/2"], "sCapHeight", None)
    if not cap:
        probe = Flatten(glyphset)
        glyphset[cmap[ord("H")]].draw(probe)
        probe._closePath()
        cap = max(y for contour in probe.contours for _x, y in contour)

    print('"""Glyph outlines for the one-letter codes and the digits.')
    print()
    print("Generated by scripts/build_glyph_outlines.py -- do not edit by hand.")
    print()
    print("Outlines are DejaVu Sans Bold, whose copyright notice this carries:")
    print()
    print("    Fonts are (c) Bitstream (see below). DejaVu changes are in public")
    print("    domain. Glyphs imported from Arev fonts are (c) Tavmjong Bah.")
    print("    Bitstream Vera Fonts Copyright (c) 2003 by Bitstream, Inc.")
    print("    Bitstream Vera is a trademark of Bitstream, Inc.")
    print()
    print("Coordinates are in cap heights with y running down from the cap line,")
    print("which is the convention the rest of the skin's text uses. ADVANCE is")
    print("each glyph's advance width in the same unit.")
    print('"""')
    print()
    print("OUTLINES = {")
    advances = {}
    for char in CHARS:
        pen = Flatten(glyphset)
        glyphset[cmap[ord(char)]].draw(pen)
        pen._closePath()
        advances[char] = font["hmtx"][cmap[ord(char)]][0] / cap
        print(f"    {char!r}: [")
        for contour in pen.contours:
            pts = ", ".join("(%.4f, %.4f)" % (x / cap, (cap - y) / cap)
                            for x, y in contour)
            print(f"        [{pts}],")
        print("    ],")
    print("}")
    print()
    print("ADVANCE = {")
    for char, adv in advances.items():
        print(f"    {char!r}: {adv:.4f},")
    print("}")


if __name__ == "__main__":
    main()
